const Post = require('../models/postModel');
const User = require('../models/userModel');
const { faker } = require('@faker-js/faker');

const generateFakeUsers = async () => {
  const users = await User.find({ isFake: true });

  // the testingUser is a user that tests the features of the app, such as making and accepting friendRequests
  const testingUser = await User.findOne({ email: 'packer.slacker@gmail.com' });

  // This array will specify if a fake generated post will contain an image using the generate property. The category specifies the type of image.
  // It will use the value of i in the for loop that generates fake posts to get the value at each index.
  const generateImageForFakePost = [
    { generate: true, category: 'cat' },
    { generate: false },
    { generate: true, category: 'cat' },
    { generate: false },
    { generate: true, category: 'dog' },
    { generate: true, category: 'cat' },
  ];

  if (users.length >= 30) {
    return;
  }

  // Generate 10 fake users

  for (let i = 0; i < 30; i++) {
    const firstName = faker.person.firstName();
    const lastName = faker.person.lastName();

    const fakePosts = [];

    for (let fakePostIndex = 0; fakePostIndex < 6; fakePostIndex++) {
      faker.seed(Date.now());
      const fakePost = {
        postMessage: '',
        img: generateImageForFakePost[fakePostIndex].generate
          ? `${faker.image.urlLoremFlickr({
              category: generateImageForFakePost[fakePostIndex].category,
            })}?random=${Math.round(Math.random() * 1000)}`
          : '', // Uses the fakePostIndex to determine if an image should be generated by selecting the boolean at the generateImageForFakePost
        author: null,
        comments: [],
        likes: { total: 0, usersLiked: [] },
      };
      for (let i = 0; i < 25; i++) {
        fakePost.postMessage += faker.word.sample() + ' ';
      }
      fakePosts.push(fakePost);
    }
    faker.seed(Date.now());

    const fakeUser = {
      name: firstName + ' ' + lastName,
      email: faker.internet.email(),
      password: faker.internet.password(),
      bio: faker.lorem.paragraph(),
      friends: [testingUser._id],
      photo: faker.image.avatarLegacy(),
      coverPhoto: faker.image.urlLoremFlickr({ category: 'animals' }),
      isFake: true,
    };

    const createdUser = await User.create(fakeUser);
    // Use the id of the createdUser as the author for the fakePosts
    const fakePostsWithAuthor = fakePosts.map((fakePost) => {
      fakePost.author = createdUser._id;
      return fakePost;
    });

    const post = await Post.create(...fakePostsWithAuthor);
    createdUser.posts = [...createdUser.posts, ...post];
    await createdUser.save();

    // Add the fake users to the testingUsers friends
    testingUser.friends = [...testingUser.friends, createdUser._id];
    await testingUser.save();
  }

  const allFakeUsers = await User.find({ isFake: true });

  // Add friends and mutualFriends to fake users

  allFakeUsers.forEach(async (fakeUser) => {
    const friends = [];
    const randomFriendCount = Math.floor(Math.random() * (20 - 10 + 1) + 10);

    for (let i = 0; i < randomFriendCount; i++) {
      let randomUserId;
      do {
        const randomIndex = Math.floor(Math.random() * allFakeUsers.length);
        randomUserId = allFakeUsers[randomIndex]._id;
      } while (friends.includes(randomUserId));

      friends.push(randomUserId);
    }

    fakeUser.friends = [...fakeUser.friends, ...friends];
    const updatedFakeUser = await fakeUser.save();
    await updatedFakeUser.save();
  });
};

module.exports = generateFakeUsers;
