const Post = require('../models/postModel');
const User = require('../models/userModel');
const { faker } = require('@faker-js/faker');

const generateFakeUsers = async () => {
  const users = await User.find({ isFake: true });
  // the testingUser is a user that tests the features of the app, such as making and accepting friendRequests
  const testingUser = await User.findOne({ email: 'packer.slacker@gmail.com' });

  // This array will specify if a fake generated post will contain an image.
  // It will use the value of i in the for loop that generates fake posts to get the value at each index.
  const generateImageForFakePost = [true, false, true, false, true, true];

  if (users.length >= 10) {
    return;
  }

  // Generate 10 fake users

  for (let i = 0; i < 10; i++) {
    // Gets fake users to populate the friends array for fake generated users
    const randomIndex = Math.floor(Math.random() * users.length);

    const firstName = faker.person.firstName();
    const lastName = faker.person.lastName();

    // Fake post in an array of 6 fake posts for fake users
    const fakePosts = [];

    for (let fakePostIndex = 0; fakePostIndex < 6; fakePostIndex++) {
      const fakePost = {
        postMessage: '',
        img: generateImageForFakePost[fakePostIndex]
          ? faker.image.animals()
          : '', // Uses the fakePostIndex to determine if an image should be generated by selecting the boolean at the generateImageForFakePost
        author: null,
        comments: [],
        likes: { total: 0, usersLiked: [] },
      };
      for (let i = 0; i < 25; i++) {
        fakePost.postMessage += faker.word.sample() + ' ';
      }
      fakePosts.push(fakePost);
    }

    const fakeUser = {
      name: firstName + ' ' + lastName,
      email: faker.internet.email(),
      password: faker.internet.password(),
      bio: faker.lorem.paragraph(),
      friends:
        users.length > 5
          ? [testingUser._id, users[randomIndex]]
          : [testingUser._id], // Generates multiple friends for some users depending on their index in the users array
      isFake: true,
      photo: faker.image.avatar(),
    };

    const createdUser = await User.create(fakeUser);
    // Use the id of the createdUser as the author for the fakePosts
    const fakePostsWithAuthor = fakePosts.map((fakePost) => {
      fakePost.author = createdUser._id;
      return fakePost;
    });

    const post = await Post.create(...fakePostsWithAuthor);
    createdUser.posts = [...createdUser.posts, ...post];
    await createdUser.save();

    // Add the fake users to the testingUsers friends
    testingUser.friends = [...testingUser.friends, createdUser._id];
    await testingUser.save();
  }
};

module.exports = generateFakeUsers;
